In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import dask.dataframe as ddf
from pandas import Series, DataFrame
%matplotlib inline
import seaborn as sn

In [2]:
import geopandas as gpd
import pandas as pd

# Load the Shapefile
gdf = gpd.read_file('/global/cfs/cdirs/m1532/Projects_MVP/geospatial/enviorment/Suicide_new/cb_2018_us_county_500k.shp')

# Convert the GeoDataFrame to a DataFrame
df = pd.DataFrame(gdf)

In [3]:
df

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,21,007,00516850,0500000US21007,21007,Ballard,06,639387454,69473325,"POLYGON ((-89.18137 37.04630, -89.17938 37.053..."
1,21,017,00516855,0500000US21017,21017,Bourbon,06,750439351,4829777,"POLYGON ((-84.44266 38.28324, -84.44114 38.283..."
2,21,031,00516862,0500000US21031,21031,Butler,06,1103571974,13943044,"POLYGON ((-86.94486 37.07341, -86.94346 37.074..."
3,21,065,00516879,0500000US21065,21065,Estill,06,655509930,6516335,"POLYGON ((-84.12662 37.64540, -84.12483 37.646..."
4,21,069,00516881,0500000US21069,21069,Fleming,06,902727151,7182793,"POLYGON ((-83.98428 38.44549, -83.98246 38.450..."
...,...,...,...,...,...,...,...,...,...,...
3228,31,073,00835858,0500000US31073,31073,Gosper,06,1186616237,11831826,"POLYGON ((-100.09510 40.43866, -100.08937 40.4..."
3229,39,075,01074050,0500000US39075,39075,Holmes,06,1094405866,3695230,"POLYGON ((-82.22066 40.66758, -82.19327 40.667..."
3230,48,171,01383871,0500000US48171,48171,Gillespie,06,2740719114,9012764,"POLYGON ((-99.30400 30.49983, -99.28234 30.499..."
3231,55,079,01581100,0500000US55079,55079,Milwaukee,06,625440563,2455383635,"POLYGON ((-88.06959 42.86726, -88.06959 42.872..."
3232,26,139,01623012,0500000US26139,26139,Ottawa,06,1459502408,2765830983,"POLYGON ((-86.26432 43.11830, -86.25103 43.118..."

In [4]:
len(df['GEOID'].unique())

3233

In [5]:
# Load the Shapefile
gdf = gpd.read_file('/global/cfs/cdirs/m1532/Projects_MVP/geospatial/climate_heatwave/gz_2010_us_050_00_500k.shp')

# Convert the GeoDataFrame to a DataFrame
df = pd.DataFrame(gdf)

In [6]:
df

,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry
0,0500000US01029,01,029,Cleburne,County,560.100,"POLYGON ((-85.38872 33.91304, -85.38088 33.873..."
1,0500000US01031,01,031,Coffee,County,678.972,"POLYGON ((-86.03044 31.61894, -86.00408 31.619..."
2,0500000US01037,01,037,Coosa,County,650.926,"POLYGON ((-86.00928 33.10164, -86.00917 33.090..."
3,0500000US01039,01,039,Covington,County,1030.456,"POLYGON ((-86.34851 30.99434, -86.35023 30.994..."
4,0500000US01041,01,041,Crenshaw,County,608.840,"POLYGON ((-86.14699 31.68045, -86.14711 31.663..."
...,...,...,...,...,...,...,...
3216,0500000US72131,72,131,San SebastiÃ¡n,Muno,70.423,"POLYGON ((-66.90748 18.25314, -66.90739 18.253..."
3217,0500000US72133,72,133,Santa Isabel,Muno,34.023,"POLYGON ((-66.37968 17.94398, -66.38029 17.943..."
3218,0500000US72137,72,137,Toa Baja,Muno,23.241,"MULTIPOLYGON (((-66.13957 18.46232, -66.13956 ..."
3219,0500000US72139,72,139,Trujillo Alto,Muno,20.764,"POLYGON ((-66.02917 18.37590, -66.02828 18.376..."
3220,0500000US72153,72,153,Yauco,Muno,68.192,"POLYGON ((-66.85229 17.95500, -66.85280 17.955..."

In [7]:
from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

import pandas as pd
import plotly.express as px

In [6]:
import geopandas as gpd
import pandas as pd

# Load the Shapefile
gdf = gpd.read_file('CityBoundaries/CityBoundaries.shp')

# Convert the GeoDataFrame to a DataFrame
df = pd.DataFrame(gdf)

In [7]:
df

,NAME,CLASS,ST,STFIPS,PLACEFIPS,POP2010,STPLFIPS,geometry
0,Pharr,city,TX,48,57200,70400,4857200,"POLYGON ((-10929531.239 3029892.718, -10929486..."
1,McAllen,city,TX,48,45384,129877,4845384,"POLYGON ((-10934477.721 3037591.957, -10934450..."
2,Edinburg,city,TX,48,22660,77100,4822660,"POLYGON ((-10924696.742 3050068.459, -10924700..."
3,Laredo,city,TX,48,41464,236091,4841464,"POLYGON ((-11090500.378 3205304.554, -11090391..."
4,Mission,city,TX,48,48768,77058,4848768,"POLYGON ((-10946610.100 3030967.743, -10946347..."
...,...,...,...,...,...,...,...,...
495,St. Paul,city,MN,27,58000,285068,2758000,"POLYGON ((-10357702.614 5620265.600, -10357675..."
496,Green Bay,city,WI,55,31000,104057,5531000,"MULTIPOLYGON (((-9780668.954 5550204.977, -978..."
497,Burlington,city,VT,50,10675,42417,5010675,"POLYGON ((-8148808.635 5541978.754, -8148756.0..."
498,Anchorage,municipality,AK,02,03000,291826,0203000,"MULTIPOLYGON (((-16722028.953 8655441.052, -16..."
499,Honolulu,city and county,HI,15,15003,953207,15003,"MULTIPOLYGON (((-17550277.418 2430210.098, -17..."

In [8]:
# Save the DataFrame to a CSV file
df.to_csv('CityBoundaries.csv', index=False)

In [11]:
city = ddf.read_csv("CityBoundaries.csv").compute()
city.head()

,NAME,CLASS,ST,STFIPS,PLACEFIPS,POP2010,STPLFIPS,geometry
0,Pharr,city,TX,48,57200,70400,4857200,"POLYGON ((-10929531.2388 3029892.7181, -109294..."
1,McAllen,city,TX,48,45384,129877,4845384,"POLYGON ((-10934477.7206 3037591.9565000013, -..."
2,Edinburg,city,TX,48,22660,77100,4822660,"POLYGON ((-10924696.7425 3050068.458799999, -1..."
3,Laredo,city,TX,48,41464,236091,4841464,"POLYGON ((-11090500.3785 3205304.5537, -110903..."
4,Mission,city,TX,48,48768,77058,4848768,"POLYGON ((-10946610.1 3030967.742800001, -1094..."

In [16]:
city = city.sort_values('POP2010', ascending = False)
city

,NAME,CLASS,ST,STFIPS,PLACEFIPS,POP2010,STPLFIPS,geometry
93,New York,city,NY,36,51000,8175133,3651000,MULTIPOLYGON (((-8260174.664100001 4950523.734...
384,Los Angeles,city,CA,6,44000,3792621,644000,MULTIPOLYGON (((-13162830.3816 3996851.7908999...
213,Chicago,city,IL,17,14000,2695598,1714000,"POLYGON ((-9758835.3821 5164429.382100001, -97..."
13,Houston,city,TX,48,35000,2099451,4835000,MULTIPOLYGON (((-10601763.8409 3450638.4487999...
105,Philadelphia,city,PA,42,60000,1526006,4260000,"POLYGON ((-8350495.5395 4868874.355999999, -83..."
...,...,...,...,...,...,...,...,...
146,Rock Hill,city,SC,45,61405,66154,4561405,"POLYGON ((-9023211.8624 4165676.721000001, -90..."
83,Schenectady,city,NY,36,65508,66135,3665508,"POLYGON ((-8227116.6778 5285934.730899997, -82..."
297,Cheyenne,city,WY,56,13900,59466,5613900,MULTIPOLYGON (((-11662763.1831 5029917.7857000...
153,Charleston,city,WV,54,14600,51400,5414600,MULTIPOLYGON (((-9095939.602 4626215.971500002...
497,Burlington,city,VT,50,10675,42417,5010675,POLYGON ((-8148808.635299999 5541978.753600001...

In [18]:
city.head(60)

,NAME,CLASS,ST,STFIPS,PLACEFIPS,POP2010,STPLFIPS,geometry
93,New York,city,NY,36,51000,8175133,3651000,MULTIPOLYGON (((-8260174.664100001 4950523.734...
384,Los Angeles,city,CA,6,44000,3792621,644000,MULTIPOLYGON (((-13162830.3816 3996851.7908999...
213,Chicago,city,IL,17,14000,2695598,1714000,"POLYGON ((-9758835.3821 5164429.382100001, -97..."
13,Houston,city,TX,48,35000,2099451,4835000,MULTIPOLYGON (((-10601763.8409 3450638.4487999...
105,Philadelphia,city,PA,42,60000,1526006,4260000,"POLYGON ((-8350495.5395 4868874.355999999, -83..."
359,Phoenix,city,AZ,4,55000,1445632,455000,MULTIPOLYGON (((-12464786.5835 3935892.7220999...
5,San Antonio,city,TX,48,65000,1327407,4865000,MULTIPOLYGON (((-10961926.1192 3407333.7444000...
324,San Diego,city,CA,6,66000,1307402,666000,MULTIPOLYGON (((-13034526.1765 3842262.7933999...
264,Dallas,city,TX,48,19000,1197816,4819000,"POLYGON ((-10738302.0381 3892916.039800003, -1..."
499,Honolulu,city and county,HI,15,15003,953207,15003,"MULTIPOLYGON (((-17550277.4182 2430210.0977, -..."
460,San Jose,city,CA,6,68000,945942,668000,MULTIPOLYGON (((-13561354.371199999 4468029.50...
30,Jacksonville,city,FL,12,35000,821784,1235000,"POLYGON ((-9061203.6483 3550012.067599997, -90..."
190,Indianapolis,city,IN,18,36003,820445,1836003,"POLYGON ((-9573964.4652 4855352.206500001, -95..."
435,San Francisco,city,CA,6,67000,805235,667000,MULTIPOLYGON (((-13623645.882399999 4546557.17...
7,Austin,city,TX,48,5000,790390,4805000,MULTIPOLYGON (((-10861676.1058 3548126.4091999...
158,Columbus,city,OH,39,18000,787033,3918000,MULTIPOLYGON (((-9232630.0859 4874580.75729999...
280,Fort Worth,city,TX,48,27000,741206,4827000,MULTIPOLYGON (((-10829953.2847 3844511.5683000...
145,Charlotte,city,NC,37,12000,731424,3712000,"POLYGON ((-8989636.2259 4217679.263499998, -89..."
168,Detroit,city,MI,26,22000,713777,2622000,MULTIPOLYGON (((-9236042.4943 5213760.83850000...
291,El Paso,city,TX,48,24000,649121,4824000,"POLYGON ((-11835874.1731 3763505.186800003, -1..."
229,Memphis,city,TN,47,48000,646889,4748000,MULTIPOLYGON (((-9991429.109 4180757.359800003...
121,Baltimore,city,MD,24,4000,620961,2404000,MULTIPOLYGON (((-8524962.2825 4752375.76420000...
79,Boston,city,MA,25,7000,617594,2507000,MULTIPOLYGON (((-7909324.5789 5202641.47150000...
469,Seattle,city,WA,53,63000,608660,5363000,MULTIPOLYGON (((-13619425.9562 6033333.6701000...
120,Washington,city,DC,11,50000,601723,1150000,"MULTIPOLYGON (((-8575935.6366 4693182.5119, -8..."
200,Nashville,"city (consolidated, balance)",TN,47,52006,601222,4752006,MULTIPOLYGON (((-9631539.1167 4319649.19349999...
298,Denver,city,CO,8,20000,600158,820000,MULTIPOLYGON (((-11680940.9737 4822323.8066999...
193,Louisville,unknown,KY,21,48006,597337,2148006,MULTIPOLYGON (((-9525994.6427 4605248.79190000...
210,Milwaukee,city,WI,55,53000,594833,5553000,"MULTIPOLYGON (((-9803168.2836 5341261.1065, -9..."
477,Portland,city,OR,41,59000,583776,4159000,MULTIPOLYGON (((-13646153.5976 5694643.1055999...
321,Las Vegas,city,NV,32,40000,583756,3240000,MULTIPOLYGON (((-12825152.5822 4329073.1001000...
276,Oklahoma City,city,OK,40,55000,579999,4055000,"POLYGON ((-10859177.2451 4255958.209100001, -1..."
316,Albuquerque,city,NM,35,2000,545852,3502000,MULTIPOLYGON (((-11876980.5993 4175202.9244000...
313,Tucson,city,AZ,4,77000,520116,477000,"POLYGON ((-12359647.5205 3803950.2556999996, -..."
378,Fresno,city,CA,6,27000,494665,627000,"MULTIPOLYGON (((-13345406.2071 4398263.0374, -..."
455,Sacramento,city,CA,6,64000,466488,664000,"POLYGON ((-13522770.9387 4674511.6888, -135225..."
393,Long Beach,city,CA,6,43000,462257,643000,MULTIPOLYGON (((-13149562.9564 3995623.4460000...
252,Kansas City,city,MO,29,38000,459787,2938000,"POLYGON ((-10529099.0959 4769529.027500004, -1..."
312,Mesa,city,AZ,4,46000,439041,446000,MULTIPOLYGON (((-12427486.9767 3947991.8898999...
111,Virginia Beach,city,VA,51,82000,437994,5182000,MULTIPOLYGON (((-8449646.4808 4376697.12799999...
179,Atlanta,city,GA,13,4000,420003,1304000,MULTIPOLYGON (((-9397505.4975 3981926.36890000...
296,Colorado Springs,city,CO,8,16000,416427,816000,MULTIPOLYGON (((-11660746.6034 4706082.0341999...
259,Omaha,city,NE,31,37000,408958,3137000,"POLYGON ((-10672493.5216 5055215.7184000015, -..."
134,Raleigh,city,NC,37,55000,403892,3755000,MULTIPOLYGON (((-8746278.5012 4262359.75190000...
53,Miami,city,FL,12,45000,399457,1245000,"MULTIPOLYGON (((-8929937.9764 2966162.7784, -8..."
150,Cleveland,city,OH,39,16000,396815,3916000,"POLYGON ((-9076183.9743 5093117.8693, -9076359..."
262,Tulsa,city,OK,40,75000,391906,4075000,"MULTIPOLYGON (((-10677907.6588 4297952.7531, -..."
437,Oakland,city,CA,6,53000,390724,653000,POLYGON ((-13594316.754900001 4541584.31769999...
488,Minneapolis,city,MN,27,43000,382578,2743000,"POLYGON ((-10384130.7622 5629581.225599997, -1..."
273,Wichita,city,KS,20,79000,382368,2079000,MULTIPOLYGON (((-10879153.8816 4507516.3162000...
279,Arlington,city,TX,48,4000,365438,4804000,"POLYGON ((-10804441.194 3870860.700099997, -10..."
380,Bakersfield,city,CA,6,3526,347483,603526,MULTIPOLYGON (((-13241451.3606 4192273.3369000...
26,New Orleans,city,LA,22,55000,343829,2255000,"POLYGON ((-10018359.834 3500085.5551000014, -1..."
418,Anaheim,city,CA,6,2000,336265,602000,"POLYGON ((-13104665.2709 4010911.454599999, -1..."
38,Tampa,city,FL,12,71000,335709,1271000,MULTIPOLYGON (((-9175517.8659 3237885.43769999...
308,Aurora,city,CO,8,4000,325078,804000,MULTIPOLYGON (((-11655676.6722 4801372.2635999...
411,Santa Ana,city,CA,6,69000,324528,669000,"POLYGON ((-13116946.2659 3998397.7849999964, -..."
233,St. Louis,city,MO,29,65000,319294,2965000,"POLYGON ((-10039025.1363 4689362.254699998, -1..."
141,Pittsburgh,city,PA,42,61000,305704,4261000,"POLYGON ((-8903020.7675 4934603.570799999, -89..."
20,Corpus Christi,city,TX,48,17000,305215,4817000,MULTIPOLYGON (((-10827645.1617 3191451.7448999...

In [20]:
city_list = city['NAME'].to_list()

In [38]:
string_to_check = 'Birmingham'

if string_to_check in city_list:
    print('The string is in the list.')
else:
    print('The string is not in the list.')

The string is in the list.

In [39]:
dict_city = {'Seattle': 1, 'Portland': 2, 'San Francisco': 3, 'Fresno': 4, 'Los Angeles': 5, 'San Diego': 6, 'Las Vegas': 7, 'Salt Lake City': 8, 
             'Phoenix': 9, 'Tucson': 10, 'Albuquerque': 11, 'El Paso': 12, 'Oklahoma City': 13, 'San Antonio': 14, 'Tulsa': 15, 'Fort Worth': 16, 
             'Austin': 17, 'Baton Rouge': 18, 'New Orleans': 19, 'Birmingham': 20, 'Memphis': 21, 'St. Louis': 22, 'Indianapolis': 23, 'Chicago': 24,
             'Milwaukee': 25, 'Detroit': 26, 'Dayton': 27, 'Louisville': 28, 'Nashville': 29, 'Atlanta': 30, 'Tampa':31, 'Miami': 32, 'Jacksonville': 33,
             'Columbia': 34, 'Raleigh': 35, 'Greensboro': 36, 'Baltimore': 37, 'Richmond': 38, 'Columbus':39, 'Pittsburgh': 40, 'Cleveland': 41, 
             'Allentown': 42, 'Albany': 43, 'Boston': 44, 'Providence': '45', 'Hartford': 46, 'Buffalo': 47, 'Rochester': 48, 'Philadelphia': 49, 
             'Charlotte': 50}

In [40]:
city_50 = pd.DataFrame(list(dict_city.items()), columns=['City', 'Number'])

city_50

              City Number
0          Seattle      1
1         Portland      2
2    San Francisco      3
3           Fresno      4
4      Los Angeles      5
5        San Diego      6
6        Las Vegas      7
7   Salt Lake City      8
8          Phoenix      9
9           Tucson     10
10     Albuquerque     11
11         El Paso     12
12   Oklahoma City     13
13     San Antonio     14
14           Tulsa     15
15      Fort Worth     16
16          Austin     17
17     Baton Rouge     18
18     New Orleans     19
19      Birmingham     20
20         Memphis     21
21       St. Louis     22
22    Indianapolis     23
23         Chicago     24
24       Milwaukee     25
25         Detroit     26
26          Dayton     27
27      Louisville     28
28       Nashville     29
29         Atlanta     30
30           Tampa     31
31           Miami     32
32    Jacksonville     33
33        Columbia     34
34         Raleigh     35
35      Greensboro     36
36       Baltimore     37
37        Richmond     38
38        Columbus     39
39      Pittsburgh     40
40       Cleveland     41
41       Allentown     42
42          Albany     43
43          Boston     44
44      Providence     45
45        Hartford     46
46         Buffalo     47
47       Rochester     48
48    Philadelphia     49
49       Charlotte     50

In [41]:
city_50 = city_50.rename(columns = {'City': 'NAME'})
city_50 = city_50.merge(city, on = ['NAME'], how = 'left')
city_50

,NAME,Number,CLASS,ST,STFIPS,PLACEFIPS,POP2010,STPLFIPS,geometry
0,Seattle,1,city,WA,53,63000,608660,5363000,MULTIPOLYGON (((-13619425.9562 6033333.6701000...
1,Portland,2,city,OR,41,59000,583776,4159000,MULTIPOLYGON (((-13646153.5976 5694643.1055999...
2,Portland,2,city,ME,23,60545,66194,2360545,MULTIPOLYGON (((-7812852.7479 5408986.73269999...
3,San Francisco,3,city,CA,6,67000,805235,667000,MULTIPOLYGON (((-13623645.882399999 4546557.17...
4,Fresno,4,city,CA,6,27000,494665,627000,"MULTIPOLYGON (((-13345406.2071 4398263.0374, -..."
5,Los Angeles,5,city,CA,6,44000,3792621,644000,MULTIPOLYGON (((-13162830.3816 3996851.7908999...
6,San Diego,6,city,CA,6,66000,1307402,666000,MULTIPOLYGON (((-13034526.1765 3842262.7933999...
7,Las Vegas,7,city,NV,32,40000,583756,3240000,MULTIPOLYGON (((-12825152.5822 4329073.1001000...
8,Salt Lake City,8,city,UT,49,67000,186440,4967000,"POLYGON ((-12438860.354 4986723.434900001, -12..."
9,Phoenix,9,city,AZ,4,55000,1445632,455000,MULTIPOLYGON (((-12464786.5835 3935892.7220999...
10,Tucson,10,city,AZ,4,77000,520116,477000,"POLYGON ((-12359647.5205 3803950.2556999996, -..."
11,Albuquerque,11,city,NM,35,2000,545852,3502000,MULTIPOLYGON (((-11876980.5993 4175202.9244000...
12,El Paso,12,city,TX,48,24000,649121,4824000,"POLYGON ((-11835874.1731 3763505.186800003, -1..."
13,Oklahoma City,13,city,OK,40,55000,579999,4055000,"POLYGON ((-10859177.2451 4255958.209100001, -1..."
14,San Antonio,14,city,TX,48,65000,1327407,4865000,MULTIPOLYGON (((-10961926.1192 3407333.7444000...
15,Tulsa,15,city,OK,40,75000,391906,4075000,"MULTIPOLYGON (((-10677907.6588 4297952.7531, -..."
16,Fort Worth,16,city,TX,48,27000,741206,4827000,MULTIPOLYGON (((-10829953.2847 3844511.5683000...
17,Austin,17,city,TX,48,5000,790390,4805000,MULTIPOLYGON (((-10861676.1058 3548126.4091999...
18,Baton Rouge,18,city,LA,22,5000,229493,2205000,"POLYGON ((-10147601.2427 3575592.9201999977, -..."
19,New Orleans,19,city,LA,22,55000,343829,2255000,"POLYGON ((-10018359.834 3500085.5551000014, -1..."
20,Birmingham,20,city,AL,1,7000,212237,107000,MULTIPOLYGON (((-9673623.5534 3947406.58219999...
21,Memphis,21,city,TN,47,48000,646889,4748000,MULTIPOLYGON (((-9991429.109 4180757.359800003...
22,St. Louis,22,city,MO,29,65000,319294,2965000,"POLYGON ((-10039025.1363 4689362.254699998, -1..."
23,Indianapolis,23,city,IN,18,36003,820445,1836003,"POLYGON ((-9573964.4652 4855352.206500001, -95..."
24,Chicago,24,city,IL,17,14000,2695598,1714000,"POLYGON ((-9758835.3821 5164429.382100001, -97..."
25,Milwaukee,25,city,WI,55,53000,594833,5553000,"MULTIPOLYGON (((-9803168.2836 5341261.1065, -9..."
26,Detroit,26,city,MI,26,22000,713777,2622000,MULTIPOLYGON (((-9236042.4943 5213760.83850000...
27,Dayton,27,city,OH,39,21000,141527,3921000,MULTIPOLYGON (((-9368513.3728 4844511.44950000...
28,Louisville,28,unknown,KY,21,48006,597337,2148006,MULTIPOLYGON (((-9525994.6427 4605248.79190000...
29,Nashville,29,"city (consolidated, balance)",TN,47,52006,601222,4752006,MULTIPOLYGON (((-9631539.1167 4319649.19349999...
30,Atlanta,30,city,GA,13,4000,420003,1304000,MULTIPOLYGON (((-9397505.4975 3981926.36890000...
31,Tampa,31,city,FL,12,71000,335709,1271000,MULTIPOLYGON (((-9175517.8659 3237885.43769999...
32,Miami,32,city,FL,12,45000,399457,1245000,"MULTIPOLYGON (((-8929937.9764 2966162.7784, -8..."
33,Jacksonville,33,city,FL,12,35000,821784,1235000,"POLYGON ((-9061203.6483 3550012.067599997, -90..."
34,Jacksonville,33,city,NC,37,34200,70145,3734200,MULTIPOLYGON (((-8607258.3363 4125954.91640000...
35,Columbia,34,city,SC,45,16000,129272,4516000,MULTIPOLYGON (((-9013551.5482 4025965.21509999...
36,Columbia,34,city,MO,29,15670,108500,2915670,MULTIPOLYGON (((-10284464.5341 4708480.0430999...
37,Raleigh,35,city,NC,37,55000,403892,3755000,MULTIPOLYGON (((-8746278.5012 4262359.75190000...
38,Greensboro,36,city,NC,37,28000,269666,3728000,MULTIPOLYGON (((-8883996.3407 4299857.59839999...
39,Baltimore,37,city,MD,24,4000,620961,2404000,MULTIPOLYGON (((-8524962.2825 4752375.76420000...
40,Richmond,38,city,VA,51,67000,204214,5167000,"MULTIPOLYGON (((-8618513.131 4506556.0748, -86..."
41,Richmond,38,city,CA,6,60620,103701,660620,MULTIPOLYGON (((-13621585.4726 4574060.3436999...
42,Columbus,39,city,OH,39,18000,787033,3918000,MULTIPOLYGON (((-9232630.0859 4874580.75729999...
43,Columbus,39,city,GA,13,19000,189885,1319000,"POLYGON ((-9428150.1971 3831597.350900002, -94..."
44,Pittsburgh,40,city,PA,42,61000,305704,4261000,"POLYGON ((-8903020.7675 4934603.570799999, -89..."
45,Cleveland,41,city,OH,39,16000,396815,3916000,"POLYGON ((-9076183.9743 5093117.8693, -9076359..."
46,Allentown,42,city,PA,42,2000,118032,4202000,MULTIPOLYGON (((-8407396.6301 4951957.71639999...
47,Albany,43,city,NY,36,1000,97856,3601000,POLYGON ((-8209030.924000001 5263282.254699998...
48,Albany,43,city,GA,13,1052,77434,1301052,"POLYGON ((-9374686.7672 3713865.1334000006, -9..."
49,Boston,44,city,MA,25,7000,617594,2507000,MULTIPOLYGON (((-7909324.5789 5202641.47150000...
50,Providence,45,city,RI,44,59000,178042,4459000,MULTIPOLYGON (((-7944864.451199999 5128637.435...
51,Hartford,46,city,CT,9,37000,124775,937000,"POLYGON ((-8091383.8784 5131501.511200003, -80..."
52,Buffalo,47,city,NY,36,11000,261310,3611000,MULTIPOLYGON (((-8779504.5415 5286672.26680000...
53,Rochester,48,city,NY,36,63000,210565,3663000,MULTIPOLYGON (((-8644998.0507 5331914.61990000...
54,Rochester,48,city,MN,27,54880,106769,2754880,MULTIPOLYGON (((-10291322.6617 5462076.2998000...
55,Philadelphia,49,city,PA,42,60000,1526006,4260000,"POLYGON ((-8350495.5395 4868874.355999999, -83..."
56,Charlotte,50,city,NC,37,12000,731424,3712000,"POLYGON ((-8989636.2259 4217679.263499998, -89..."

In [42]:
city_50.to_csv('50_city_boundaries.csv')